language: ruby
rvm:
  - 2.5.1
before_install:
  - gem install bundler -v 1.15.2
deploy:
  provider: heroku
  api_key:
    secure: GESvT6aXXcnQoedaGbH/TlyRQiI3tVYEubtAQALeJZuOgFi0aBd6MUYl4RF9l0xJlW3Jr+yjRVB/RTOBQeiaqw4iaZ4i5P8odIxi8BSSe/8hTBxrEVMjBkuLciovzCW9ZQReDk9f1z2I09H/YyZW3KVlCsn3+qir5n0nvWzB6vgR86k4yK8C+CQnqXhdW4WIDq0G2BlhPy2HwHQ4yAsVZCT8LZOI9VIsDvly5LdoBzMzlQQVg/lnKBiIxAV9gj2S6w78HAay/ShP9hI98ddWFvRX7+RxlsmmYCbp6iZrKTzn0ShQ7R3qaI8wEnf2EMoPxTvPeqDY0CW8zQg7Zco7WJCM9dkBDTOT3/y+uet4ZIoEorKMYw+7e+Icc9+c/SCHMjRILbejWxFZC35bhG2tKpXH54Am2dXwdcmcw5BHc6C1QqDS4oCYSDiO06Mkpoku7eQblJXkUzwjB+q+5NSwZUEjoysGvzABGtp0l8Scb2vMdhZ9/4tSMDKBk0mgbHlT9dEPI7TxJG/keynL2lzjuRvD7+Fv9w65KOcnTJJXSQ9wpz/fpAslYEsfmjOs2MZVKFDo8HOZmGNx3nIWdflAZfFi/HKNj4aaek1qieG8dUQ5Vij8hKOBFEvWTbRex0Wv4P0Liqazxy8QIHYzkK35Z5jqsUOpw8UBdQMX7DsPtck=
  app:
    staging: sumfinance-staging
    production: sumfinance
branches:
  only:
  - staging
  - production
# before_script:
#   - bundle exec rake db:test:prepare
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake